# Generated by Django 5.0.6 on 2024-07-02 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, choices=[('Small', 'Маленький'), ('Medium', 'Средний'), ('Large', 'Большой')], max_length=100, null=True)),
                ('max_flavors', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Creamy', 'Сливочное мороженое'), ('Ice_Pop', 'Фруктовый лёд'), ('Eskimo', 'Эскимо')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamAtStick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Ice_Pop', 'Фруктовый лёд'), ('Eskimo', 'Эскимо')], max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecream_bar.flavor')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icecream_bar.topping')),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamInContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecream_bar.container')),
                ('flavors', models.ManyToManyField(to='icecream_bar.flavor')),
                ('toppings', models.ManyToManyField(blank=True, to='icecream_bar.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icecream_bar.drink')),
                ('ice_cream_at_stick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icecream_bar.icecreamatstick')),
                ('ice_cream_in_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icecream_bar.icecreamincontainer')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ManyToManyField(to='icecream_bar.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('New', 'Новый'), ('Completed', 'Завершен')], default='New', max_length=50)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icecream_bar.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
