# Generated by Django 5.0.6 on 2024-07-09 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='Container/')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='Flavor/')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='Topping/')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IceCreamInContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Стоимость')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('container',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecream_bar.container',
                                   verbose_name='Основа')),
                ('flavor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor1',
                                              to='icecream_bar.flavor', verbose_name='Вкус')),
                ('flavor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor2',
                                              to='icecream_bar.flavor', verbose_name='Вкус')),
                ('flavor3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor3',
                                              to='icecream_bar.flavor', verbose_name='Вкус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecream_bar.topping',
                                              verbose_name='Добавка')),
            ],
        ),
    ]
