# Generated by Django 5.0.6 on 2024-07-02 22:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream_bar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='icecreamatstick',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='icecreamatstick',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ice_cream_at_stick',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ice_cream_in_container',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='container',
            name='max_flavors',
        ),
        migrations.RemoveField(
            model_name='container',
            name='size',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='type',
        ),
        migrations.RemoveField(
            model_name='icecreamincontainer',
            name='flavors',
        ),
        migrations.RemoveField(
            model_name='icecreamincontainer',
            name='toppings',
        ),
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.ImageField(blank=True, upload_to='Container/'),
        ),
        migrations.AddField(
            model_name='container',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavor',
            name='image',
            field=models.ImageField(blank=True, upload_to='Flavor/'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecreamincontainer',
            name='flavor1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flavor1', to='icecream_bar.flavor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecreamincontainer',
            name='flavor2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flavor2', to='icecream_bar.flavor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecreamincontainer',
            name='flavor3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flavor3', to='icecream_bar.flavor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecreamincontainer',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecreamincontainer',
            name='topping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='icecream_bar.flavor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecreamincontainer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='icecream_bar.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='image',
            field=models.ImageField(blank=True, upload_to='Topping/'),
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icecreamincontainer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='IceCreamAtStick',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
