# Generated by Django 5.0.6 on 2024-07-07 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream_bar', '0002_remove_order_cart_remove_item_drink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecreamincontainer',
            name='price',
        ),
        migrations.AlterField(
            model_name='icecreamincontainer',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecream_bar.container', verbose_name='Основа'),
        ),
        migrations.AlterField(
            model_name='icecreamincontainer',
            name='flavor1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor1', to='icecream_bar.flavor', verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='icecreamincontainer',
            name='flavor2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor2', to='icecream_bar.flavor', verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='icecreamincontainer',
            name='flavor3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor3', to='icecream_bar.flavor', verbose_name='Вкус'),
        ),
        migrations.AlterField(
            model_name='icecreamincontainer',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icecream_bar.topping', verbose_name='Добавка'),
        ),
        migrations.AlterField(
            model_name='icecreamincontainer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
