# Generated by Django 5.0.6 on 2024-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream_bar', '0002_alter_cup_price_alter_icecream_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/IceCream'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/IceCream'),
        ),
        migrations.AddField(
            model_name='topping',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/IceCream'),
        ),
    ]
